== Grundbausteine einer Steuerung - Zeitschaltuhren und Überwachung

Du hast jetzt also die ersten eigenen Geräte in FHEM integriert und kannst z.B. deinen Verstärkter ein- und ausschalten oder die Lautstärke regulieren. +
Damit ist FHEM schon mal sowas wie eine "erweiterte Fernbedienung" für deine IoT-fähigen Geräte.

Um daraus jetzt *eine Heimautomatisierung* mit der Betonung auf *Automatisierung* zu machen, solltest du ein paar Grund-"Bauteile" kennen lernen, die in vielerlei Variationen sowas die die DNA jeder Automatisierungslösung darstellen. Bei der DNA kennt man vier Buchstaben, bei der Steuerung haben wir auch je nach Zählweise zwischen einem und fünf Grundelementen, aus denen praktisch alles aufgebaut wird, wobei die beiden letzten streng genommen schon Erweiterungen bzw. einfache Kombinationen der ersten beiden sind:

=== Schalten nach Uhrzeit: at

Xxx text und etwas info

=== Ereignisse auswerten: notify

Xxx text und etwas info

=== Wichtige Erweiterungen dieser Grundformen

==== Zweipunktregler (z.B. THRESHOLD)

Xxx text und etwas info

==== Ausfallerkennung (watchdog)

Xxx text und etwas info

==== Steuerung über Änderungsgeschwindigkeit (PID20)

Xxx text und etwas info

'''''
=== Komplexere Logikmodule

In FHEM gibt es nicht nur Module, die diesen vier Grundelementen entsprechen, sondern auch eine ganze Anzahl von alternativen Modulen. Neben Modulen, die ganz spezielle Zielrichtungen kennen (wie z.B. die Module aus der Residents-Familie, die wir beim Rundgang durch die Demo-Konfiguration kennengelernt haben, oder https://wiki.fhem.de/wiki/WeekdayTimer[AutoShuttersControl], das zur Rollladensteuerung eingesetzt werden kann), seien an der Stelle folgende Module kurz erwähnt:

* https://wiki.fhem.de/wiki/WeekdayTimer[WeekdayTimer] bildet eine Wochenzeitschaltuhr nach und kann universell verwendet werden. Ein spezieller Anwendungsbereich ist die Steuerung von Heizkörperthermostaten, für die das Modul ursprünglich entwickelt wurde. Es steuert in der Regel genau ein anderes Gerät wie eine Lampe oder ein Thermostat. +
* https://fhem.de/commandref_modular_DE.html#Timer[Timer] kann mehrere einzelne Timer verwalten, die beliebig kombiniert werden können. Hat eine grafische Konfigurationsmöglichkeit. +
* https://wiki.fhem.de/wiki/DOIF[DOIF] und https://wiki.fhem.de/wiki/MSwitch[MSwitch] sind beide jeweils sehr universelle Module, die Zeit- und Ereignissteuerungen sowie Kombinationen von beidem ermöglichen. Aufgrund der universellen Verwendbarkeit ist die Konfiguration dieser Module teils sehr komplex, wenn schwierigere Aufgaben zu lösen sind. +
* https://wiki.fhem.de/wiki/Modul_YAAHM[YAAHM] dient ebenfalls vorrangig der Verwaltung von Timern, die sich an typischen Tagesabläufen orientieren, kann das aber für das gesamte Haus übernehmen unter Berücksichtigung weiterer Bedingungen wie z.B. Jahreszeiten usw.. +
* https://fhem.de/commandref_modular.html#RandomTimer[RandomTimer] bildet eine Zeitschaltuhr mit Zufallselementen nach und wird häufig in der Anwesenheitssimulation verwendet; steuert in der Regel genau ein anderes Gerät, z.B. eine Leuchte. +
* alarmclock (ANMERRKUNG v. Schotty: gibt's hierfür keinen Link/Eintrag?) kann diverse Wecker-Automationen in FHEM abbilden.

.Meine Empfehlungen zur Modulauswahl
****
Bevor du dich in spezielle Module einarbeitest, solltest du wenigstens ein paar einfache at und notify (ANMERKUNG v. Schotty: at & notify hier gerne irgendwie hervorgehoben - kursiv oder sonstwie) erfolgreich konfiguriert haben. Scheue auch nicht davor zurück, die Perl-Syntax wenigstens in den Grundzügen zu erlernen! Ich habe auch zuerst einen großen Bogen um die direkte Verwendung dieser Programmiersprache gemacht, aber selbst einige Modulautoren beliebter Universal-Module empfehlen Perl-Code-Teile einzusetzen, wenn es um die Lösung komplexer Probleme geht. Es ist zwar so, dass praktisch alle Module irgendwie dazu dienen, dem User die meiste Programmierarbeit abzunehmen und den "lästigen Umweg" über Perl abzukürzen. Aber gerade was universelle Module zur Kombination von Zeit- und Ereignissteuerung angeht, habe ich im Ergebnis viel Zeit mit dem mehr oder weniger erfolglosen Versuch verbraucht, die Syntax eines dieser Module zu verstehen, nur um am Ende dann doch Perl zu lernen und die schlichte Eleganz von devspec, FILTER und regex zu erkennen.

Als Anfang genügen ein paar `if (...) { } elsif (...) { } else {}` ``Einzeiler''(ANMERKUNG v. Schotty: Dies Art der 'Auszeichnung' mit den ungleichen Zeichen ` und ' hatte ich auch in <<fhem-grundlagen>> gesehen - jetzt nutze ich zur visuellen Kontolle gerade einen anderen Editor und mir fällt dabei auf, dass die Zeichen als solche dargestellt werden, das Wort dazwischen, also hier Einzeiler, erscheint unverändert im Output - keine Ahnung, ob das an falschen Zeichen liegt?), vielleicht verbunden mit einfachen eigenen myUtils-Funktionen (ANMERKUNG v. Schotty: myUtils gerne verlinken, wenn dazu noch ein Kap/eine Erklärung irgendwo anders kommt (wovon ich ausgehe)), über die auf Reading- und/oder Attributwerte zugegriffen wird (ReadingsVal() und ReadingsNum()) (ANMERKUNG v. Schotty: Auch hier die Ausdrücke gern anders formatiert darstellen!), das war es schon…

Zur Erinnerung: Die "DNA" aller Module ist aus _at_ (in fhem.pl: `InternalTimer()`) und _notify_ (in fhem.pl: `notifyfn()`) aufgebaut - funktioniert also irgendwas nicht so, wie es soll, ist entweder deine Anweisung an das Modul nicht so, wie das das haben will, oder es liegt wirklich ein bug vor. (ANMERKUNG v. Schotty: hmm, irgendwie sehr verschachtelt und etwas komisch formuliert - wie das das haben will..; Auch hier wieder das englische Wort bug kleingeschrieben - in dieser Verwendung würde ich es ebenfalls mit einem Großbuchstaben beginnend schreiben, also Bug..) Letzteres ist aber die Ausnahme, nicht die Regel… Du solltest also versuchen zu verstehen, wie diese beiden DNA-Bausteinchen in den Konfigurationsmöglichkeiten eines Moduls wiederzufinden sind, dann solltest du in der Lage sein, jedes Modul zu konfigurieren und kannst auch die _list_-Ausgaben zu den Devices besser verstehen.
****

