== Grundbausteine einer Steuerung - Zeitschaltuhren und Überwachung

Du hast jetzt also die ersten eigenen Geräte in FHEM integriert und kannst z.B. deinen Verstärkter ein- und ausschalten oder die Lautstärke regulieren. +
Damit ist FHEM schon mal sowas wie eine "erweiterte Fernbedienung" für deine IoT-fähigen Geräte.

Um daraus jetzt *eine Heimautomatisierung* mit der Betonung auf *Automatisierung* zu machen, solltest du ein paar Grund-"Bauteile" kennen lernen, die in vielerlei Variationen sowas die die _DNA_ jeder Automatisierungslösung darstellen. Bei der _DNA_ kennt man vier Buchstaben, bei der Steuerung haben wir auch je nach Zählweise zwischen einem und fünf Grundelementen, aus denen praktisch alles aufgebaut wird, wobei die drei letzten streng genommen schon Erweiterungen bzw. einfache Kombinationen der ersten beiden sind:

=== Schalten nach Uhrzeit: at

Ein häufiger Anwendungsfall ist das Schalten von Geräten zu festgelegten, sich ggf. wiederholenden Zeitpunkten. Dazu  steht in FHEM das _Hilfs-Modul_ `at` zur Verfügung. Die commandref liefert dazu folgende Syntax: 
`define <name> at [<timespec>|<datespec>] <command>`. Eine einfache Zeit-Einschalt-Anweisung könnte also z. B. `define LampeAnUm1700 at 17:00:00 set lamp on` lauten. Ist die angegebene Uhrzeit erreicht, wird die Anweisung genau einmal ausgeführt. Damit ist das _Device_ erfolgreich abgearbeitet und wird gelöscht. Auch Wiederholungen sind möglich, z.B. täglich um 17:00. Dazu wird der Uhrzeit ein * vorangestellt: `define LampeTaeglichAn at *17:00:00 set lamp on`. 

_at_ kennt einen speziellen `modify`-Befehl`, der dazu dient, den Zeitpunkt zu ändern, ohne den Befehls-Teil erneut angeben zu müssen: `modify LampeTaeglichAn *17:30:00`

Über die absolute Angabe von Schaltzeiten (um 17:00) hinaus erlaubt  _at_ auch relative Angaben. Dies wird durch ein vorangestelltes Plus-Zeichen erreicht. Also „in 10 Minuten“: `define a5 at +00:10:00 set lamp on`. Die Kombination von + und * bewirkt dann z.B. „alle 10 Minuten“, hier für 30 Sekunden: `define a6 at +*00:10:00 set lamp on-for-timer 30`.

Für solche Durchläufe kann auch die gewünschte Anzahl der Wiederholungen in geschweiften Klammern angegeben werden:
`define a7 at +*{3}00:00:02 set lamp on-for-timer 1'  # drei mal blinken
(drei mal alle 2 Sekunden für 1 Sekunde einschalten).
In der _commandref_ sind hierzu weitere Beispiele genannt, die auch Abhängigkeiten von Wochenenden, Sonnenauf- und -untergängen aufzeigen – dies erfordert einfache Programmierung, zu der wir später noch kommen.


=== Ereignisse auswerten: notify

Xxx text und etwas info

=== Wichtige Erweiterungen dieser Grundformen

==== Zweipunktregler (z.B. THRESHOLD)

Xxx text und etwas info

==== Ausfallerkennung (watchdog)

Xxx text und etwas info

==== Steuerung über Änderungsgeschwindigkeit (PID20)

Xxx text und etwas info

'''''
=== Komplexere Logikmodule

In FHEM gibt es nicht nur Module, die diesen vier Grundelementen entsprechen, sondern auch eine ganze Anzahl von alternativen Modulen. Neben Modulen, die ganz spezielle Zielrichtungen kennen (wie z.B. die Module aus der Residents-Familie, die wir beim Rundgang durch die Demo-Konfiguration kennengelernt haben, oder https://wiki.fhem.de/wiki/WeekdayTimer[AutoShuttersControl], das zur Rollladensteuerung eingesetzt werden kann), seien an der Stelle folgende Module kurz erwähnt:

* https://wiki.fhem.de/wiki/WeekdayTimer[WeekdayTimer] bildet eine Wochenzeitschaltuhr nach und kann universell verwendet werden. Ein spezieller Anwendungsbereich ist die Steuerung von Heizkörperthermostaten, für die das Modul ursprünglich entwickelt wurde. Es steuert in der Regel genau ein anderes Gerät wie eine Lampe oder ein Thermostat. +
* https://fhem.de/commandref_modular_DE.html#Timer[Timer] kann mehrere einzelne Timer verwalten, die beliebig kombiniert werden können. Hat eine grafische Konfigurationsmöglichkeit. +
* https://wiki.fhem.de/wiki/DOIF[DOIF] und https://wiki.fhem.de/wiki/MSwitch[MSwitch] sind beide jeweils sehr universelle Module, die Zeit- und Ereignissteuerungen sowie Kombinationen von beidem ermöglichen. Aufgrund der universellen Verwendbarkeit ist die Konfiguration dieser Module teils sehr komplex, wenn schwierigere Aufgaben zu lösen sind. +
* Das neuere https://forum.fhem.de/index.php/topic,110165.msg1041882.html#msg1041882[combine] kann ebenfalls ein Zielgerät abhängig von einer Mehrzahl von Informationen steuern +
* https://wiki.fhem.de/wiki/Modul_YAAHM[YAAHM] dient ebenfalls vorrangig der Verwaltung von Timern, die sich an typischen Tagesabläufen orientieren, kann das aber für das gesamte Haus übernehmen unter Berücksichtigung weiterer Bedingungen wie z.B. Jahreszeiten usw.. +
* https://fhem.de/commandref_modular.html#RandomTimer[RandomTimer] bildet eine Zeitschaltuhr mit Zufallselementen nach und wird häufig in der Anwesenheitssimulation verwendet; steuert in der Regel genau ein anderes Gerät, z.B. eine Leuchte. +
* https://fhem.de/commandref_modular.html#alarmclock[alarmclock] kann diverse Wecker-Automationen in FHEM abbilden.



.Meine Empfehlungen zur Modulauswahl
****
Bevor du dich in spezielle Module einarbeitest, solltest du wenigstens ein paar einfache `at` und `notify` erfolgreich konfiguriert haben. Scheue auch nicht davor zurück, die Perl-Syntax wenigstens in den Grundzügen zu erlernen! Ich habe auch zuerst einen großen Bogen um die direkte Verwendung dieser Programmiersprache gemacht, aber selbst einige Modulautoren beliebter Universal-Module empfehlen Perl-Code-Teile einzusetzen, wenn es um die Lösung komplexer Probleme geht. Es ist zwar so, dass praktisch alle Module irgendwie dazu dienen, dem User die meiste Programmierarbeit abzunehmen und den "lästigen Umweg" über Perl abzukürzen. Aber gerade was universelle Module zur Kombination von Zeit- und Ereignissteuerung angeht, habe ich im Ergebnis viel Zeit mit dem mehr oder weniger erfolglosen Versuch verbraucht, die Syntax eines dieser Module zu verstehen, nur um am Ende dann doch Perl zu lernen und die schlichte Eleganz von devspec, FILTER und regex zu erkennen.

Als Anfang genügen ein paar `if (...) { } elsif (...) { } else {}` 'Einzeiler', vielleicht verbunden mit einfachen eigenen link:#99_myUtils-pm-basics[_myUtils_-Funktionen], über die auf Reading- und/oder Attributwerte zugegriffen wird (`ReadingsVal()` und `ReadingsNum()`), das war es schon…

Zur Erinnerung: Die "DNA" aller Module ist aus _at_ (in fhem.pl: `InternalTimer()`) und _notify_ (in fhem.pl: `notifyfn()`) aufgebaut - funktioniert also irgendwas nicht so, wie es soll, entspricht entweder deine Anweisung an das Modul nicht den Erwartungen des Modulcodes, oder es liegt wirklich ein _Bug_ vor, also ein Programmfehler. Letzteres ist aber die Ausnahme, nicht die Regel… Du solltest also versuchen zu verstehen, wie diese beiden DNA-Bausteinchen in den Konfigurationsmöglichkeiten eines Moduls wiederzufinden sind, dann solltest du in der Lage sein, jedes Modul zu konfigurieren und kannst auch die _list_-Ausgaben zu den Devices besser verstehen.
****



