[[hardware-teil-1]]
Hardware – Teil 1
-----------------

[[wo-anfangen-eine-bestandsaufnahme]]
Wo anfangen? Eine Bestandsaufnahme
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Viele neue User interessieren sich zunächst einmal dafür, was sie anschaffen sollen, um überhaupt erstmal einen Einstieg zu haben. Mein Vorschlag: Wir schauen erstmal, was du schon hast - das nehmen wir dann einfach als „erstes Testgerät“. Da es ohne Server nicht geht, kommen nach einigen Hilfestellungen zur Festegung bzw. Beschaffung dieses „Erstgeräts“ zunächst ein paar Hinweise zur Serverauswahl, dann werden wir mit dem Erstgerät einige FHEM-Grundlagen erarbeiten. Ein paar Handreichungen zur Auswahl des „passenden“ Hausautomatisierungssystems finden sich dann weiter hinten.

Vor allem zum ersten Kennenlernen von FHEM kannst du dir erstmal die Frage stellen, was du eigentlich schon direkt verwenden könntest. Denn ein großer Teil der elektronischen Dinge, die du in den letzten 10 Jahren gekauft hast, steht unter dem dringenden Verdacht, dass das *_irgendwie_* – meistens sogar ohne weiteres – in FHEM integrierbar ist. Erster Schritt sollte daher eine Bestandsaufnahme all dessen sein, für das Du irgendeine App auf dem Handy installiert hast, z.B.:

* einen Multimediareceiver o.ä., verbreitete Marken wie _Yamaha_, _Onkyo_ und _Samsung_ kommen hier ebenso in Frage wie _Sonos_-Systeme oder manche WLAN-Küchenradios vom örtlichen Lebensmitteldiscounter;
* ZigBee-Bridges, z.B. _Philips HUE_ oder ein _Tradfri-Gateway_ von _IKEA_, eventuell hast Du auch eine _phoscon_-App?
* direkt über WLAN schaltbare Leuchtmittel oder Steckdoseneinsätze, etwa einen _Shelly-Plug_;
* Bluetooth-Sensoren oder fernsteuerbare Heizkörperthermostate...;

Daneben gibt es eventuell manches, für das du zwar keine App hast, das aber trotzdem eventuell zumindest als Datenquelle genutzt werden kann oder sogar steuerbar sein könnte. In diese Kategorie fallen z.B.:

* alte 433MHz-Geräte aus dem Baumarkt, die mit einer Fernbedienung zu bedienen sind;
* über Funk steuerbare Rollläden, insbesondere der Marke _Somfy_;
* Dunstabzugshauben mit Fernbedienung;
* Temperatursensoren, vor allem solche, die ihre Messwerte an eine Basisstation senden;
* Zentralheizungsgeräte, vor allem neuerer Baureihen;
* AV-Geräte mit einer Infrarot-Fernbedienung
* ...;

FHEM kann meist alle diese Dinge ebenfalls mit auswerten und steuern. Nur: Der Weg dahin kann sehr unterschiedlich sein. Wenn du noch keine oder wenig Erfahrung hast, empfehle ich für den Start und das erste Kennenlernen der Steuerung realer Geräte mit FHEM etwas, für das du eine App hast. Die Basis-Funktionalität in FHEM entspricht – bei richtiger Konfiguration – nämlich häufig ziemlich genau dem, was auch die App bietet. Für die Wahl des „Erstgeräts“ ist es optimal, wenn einige wenige Funktionen gegeben sind, aber nicht gleich viele reale Geräte gesteuert werden können. In meinem Haushalt habe ich z.B. einen netzwerkfähigen HiFi-Receiver der Marke _Yamaha_, der sich u.a. mit der App _multicast_ steuern lässt. Dieser wäre ideal, denn er hat zwei getrennt schaltbare Zonen, man kann unterschiedliche Quellen für die Zonen wählen und unterschiedliche Lautstärken einstellen. Gut geeignet wäre auch ein smartes TV-Gerät, bei dem man auch unterschiedliche Programme und Lautstärken kann. Ebenfalls geeignet, aber für einen Einstieg deutlich unübersichtlicher wäre eine _HUE_- oder _Tradfri_-Bridge, vor allem, wenn bereits viele Geräte daran angelernt sind. Nach dem ersten Überblick über FHEM werden wir meinen Yamaha-Receiver als Beispielgerät verwenden, du musst dann eben die Kommandos für dein „Einsteigergerät“ anpassen. Wenn du gar kein Gerät hast und etwas Einfaches suchst, würde ich zu einem oder zwei Steckdoseneinsätzen mit Messfunktion aus der _Shelly_ Produktlinie raten. Hast du bereits etwas Ähnliches, das schon mit einer firmware ausgestattet ist, die ein Protokoll namens _MQTT_ nutzen kann, ist auch das ok. Allerdings hat auch dieser Rat einen Pferdefuß, auf den wir später nochmal zurückkommen werden: Diese Geräte werden über das WLAN gesteuert...;

Hinweis: Jetzt kann es sein, dass du feststellst, dass es für das Gerät, das du eben als Testgerät ausgewählt hast, mehrere Varianten gibt, wie es in FHEM eingebunden werden kann! Wenn das der Fall ist, hast du etwas Wichtiges gelernt: Es gibt selten nur einen Weg, etwas umzusetzen, und häufig gibt es nicht „den besten“...! Dies schon alleine deshalb, weil es für die Entscheidung der Frage, was „das Beste“ ist, darauf ankommt, wie das konkrete Umfeld aussieht. Du wirst also ziemlich oft die _Qual der Wahl_ haben, wir werden noch ein paar Mal darauf zurückkommen.

[[die-qual-der-wahl-1---server]]
Die Qual der Wahl 1 - Server!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Die erste Wahl, vor die du gestellt bist, ist die, welche Art Server du eigentlich einsetzen willst. Dazu muß man verstehen, dass FHEM in Perl geschrieben ist, und Perl-Interpreter für praktisch alle verbreiteten Betriebssysteme verfügbar sind. FHEM selbst ist nur ein Perl-Script mit ein paar Plugins, die wir  xref:Modul[_Module_] 
//(ANMERKUNG v. Schotty: Wenn hier die "FHEM"-Module gemeint sind, dann evtl "Module" kennzeichnen und auf den späteren Abschnitt mit der Erklärung verlinken) 
nennen. Das sind ein paar Dateien, die man im Prinzip irgendwohin speichern kann und dann mit dem Perl-Interpreter startet. Du kannst also ohne Weiteres eine aktuelle Perl-Umgebung für Windows herunterladen (link zur Anleitung mit 32bit-Strawberry-Perl), FHEM als _zip_ holen, das in ein beliebiges Verzeichnis entpacken und zum Testen loslegen. Wenn du nur mal reinschnuppern und gar kein Geld ausgeben willst, wäre das eine empfehlenswerte Variante. Einfacher geht es, wenn du z.B. einen PC oder ein Laptop mit einem Linux-Betriebssystem besitzt - da ist der Perl-Interpreter in der Regel schon installiert. Es kann dann nur sein, dass einige wenige Perl-Module nachinstalliert werden müssen, Details dazu findest du in den Installationsanleitungen. Wenn du also einen Linux-Rechner hast und nur mal Testen willst: zip-Datei entpacken und wir können loslegen.

Für das Folgende ist eine Windows-Umgebung oder ein beliebiger Linux-Rechner bereits ausreichend.

Willst du nicht nur mal kurz antesten, sondern FHEM etwas intensiver kennenlernen, brauchst du eine Plattform, die rund um die Uhr läuft. Wenn du bereits einen (Linux-)-Server betreibst, könntest du den verwenden, und FHEM z.B. in der https://forum.fhem.de/index.php/topic,89745.0.html["docker"-Variante] installieren.

Wenn dir das alles nichts oder wenig sagt, gibt es eine einfache Empfehlung: Besorge dir einen Raspberry Pi. ABER: Das ist eine *_Empfehlung mit Pferdefuß_*! Genauer: Die hat gleich mehrere große Haken und ist eigentlich eher eine Notlösung, eine Art *_kleinster gemeinsamer Nenner_*...;

* Zum einen musst du dich in das *Betriebssystem* dafür einarbeiten: _Linux_. Wir werden später darauf zurückkommen...;
* Zum anderen ist auch die Hardware an sich nur bedingt tauglich. Insbesondere ungünstig ist es, dass die Daten und das Betriebssystem auf einer SD-Karte gespeichert werden. Das ist alles andere als optimal: Es gibt im FHEM-Forum alle paar Wochen User, die über unerklärliche Fehler berichten, die letztlich auf eine kaputte SD-Karte zurückzuführen sind. Man kann zwar auch über USB eine SSD-Festplatte anschließen, das verringert den _wear-out_ durch häufige Schreibzugriffe auf denselben Bereich des Flash-Speichers, aber zum einen ist die Konfiguration eines solchen Setups nicht trivial, und zum anderen Linux reagiert auf Störungen im Zugriff auf Systemlaufwerke sehr empfindlich. Da aber ausgerechnet die Stromversorgung der USB-Schnittstellen am Pi ebenfalls nicht optimal ist, lohnt der Aufwand für Einsteiger nicht (es sei betont: Das ist meine Meinung!).

Du merkst dir zum Thema _Raspberry Pi_ aber bitte an der Stelle drei Dinge:

1. Ziehe niemals den Stecker des Pi, wenn er nicht sauber heruntergefahren wurde. Das führt häufig zu defekten SD-Karten!
2. Wenn Du FHEM im produktiven Einsatz hast und es nicht mehr missen willst, brauchst Du unbedingt Backups, die nicht auf der SD-Karte liegen und mußt jederzeit in der Lage sein, eine andere Karte in den Pi zu stecken und mit der - mehr oder weniger 1:1 - weiterzumachen...;
3. Finger weg von den PI-GPIO!

Den letzten Punkt verstehst du vermutlich nicht gleich: Der Pi ist ein _Bastelrechner_, an den man _alles mögliche_ an Hardware auch direkt anschließen kann, man muss nur manchmal ein paar Kleinigkeiten am Betriebssystem umkonfigurieren, und schon läuft das. Das führt aber dazu, dass man die Steuerungslogik (FHEM) sehr eng an ein bestimmtes Hardwaresystem bindet (Raspberry Pi). Viele FHEM-Nutzer stellen aber irgendwann fest, dass sie doch lieber eine andere Hardwareplattform einsetzen wollen. Dann wird es kompliziert, beide Teile wieder zu trennen. Außerdem können sich die Methoden ändern, wie die _GPIO_ angesprochen werden, wenn eine neue Hardwarerevision erscheint oder eine grundlegende Versionsänderung des Betriebssystems stattgefunden hat. Kurz: Mittelfristig wird es Probleme machen, also lass‘ es besser!

.Tipp
****
Die einzige Hardware-Erweiterung für GPIO am Pi, die ich empfehlen würde, ist eine https://wiki.fhem.de/wiki/Raspberry_Pi#Echtzeituhr[RTC]! Die brauchst du aber auch nur deswegen, weil die schlicht von den Machern des Pi aus unerfindlichen Gründen _eingespart_ wurde; bei den meisten anderen Alternativen ist bereits eine RTC verbaut.
****

.Für später 1
NOTE: Will man (meist günstige) Sensorik einsetzen, die man mit Pi-GPIO's auslesen könnte, ist für diese Sensoren in der Regel auch eine _library_ für _Arduino_ verfügbar. Dann kann und sollte man einen _Microcontroller_ programmieren, der diese Sensoren ausliest und das Ergebnis an FHEM übermittelt. Das mag für dich als Anfänger zunächst befremdlich klingen, ist aber im Ergebnis meist nicht besonders schwer zu erlernen und umzusetzen, häufig gibt es dafür fertige Bauvorschläge! Ein paar Links dazu: https://www.mysensors.org/build[MySensors]: Einfache Bauanleitungen für typische Sensorik, auch für https://tasmota.github.io/docs/#/Home[Tasmota] oder https://www.letscontrolit.com/wiki/index.php?title=ESPEasy[ESPEasy] zu gebrauchen. Typische Pi-GPIO-Anwendungen lassen sich insbesondere sehr einfach auch über https://fhem.de/commandref_modular.html#ArduCounter[ArduCounter] (Auswerten von S0-Zählimpulsen) und https://wiki.fhem.de/wiki/Arduino_Firmata[Firmata] (direkte Auswertung der PINs externer Microcontroller mittels Perl) verwirklichen.

.Für später 2
NOTE: Es gibt eine ganze Anzahl von stromsparenden Alternativen zum Raspberry Pi. Neben diversen anderen https://de.wikipedia.org/wiki/Einplatinencomputer[SBC's] auf ARM-Basis gibt es einige x86-Systeme. Bei der Auswahl solltest du dann allerdings darauf achten, dass die gewählte Plattform vollständig Linux-kompatibel ist, was v.a. bei neu erscheinenden Intel NUC-Systemen nicht immer gleich bei Erscheinen der Fall ist. Es ist in der Regel empfehlenswert (und auch ausreichend), eine Version zu wählen, die bereits einige Zeit am Markt verfügbar ist, und deren Mucken bereits bekannt bzw. ausgemerzt sind.

[[linux---nimms-lite]]
Linux - nimm's lite!
~~~~~~~~~~~~~~~~~~~~

Linux mag für dich - wie für viele Einsteiger in die Welt der Hausautomatisierung - völliges Neuland sein, um das du gerne rumkommen würdest. Du kannst FHEM - im Unterschied zu vielen anderen HA-Lösungen - auch auf einem Windows-Rechner laufen lassen. Das hat aber zumindest einen großen Nachteil: Die meisten anderen User tun genau das nicht. Die verwenden zu >95% ein Debian-basiertes Linux. Bei manchen Fragen kann dann von diesen 95% keiner helfen...; Daher: Nimm' ein Linux und erarbeite dir nach und nach das notwendige Wissen, um deinen Server zu administrieren! Nimm auch nicht irgendeines, sondern entweder Raspbian - und zwar genauer: In der lite-Version, also ohne GUI! - oder ein Debian oder Ubuntu, falls du eine x86-basierte Hardware gefunden hast. Auch in letzterem Fall gilt: Ohne GUI!

.Für später
NOTE: Solltest du ein „richtiges“ x86-System einsetzen wollen, findest du im Wiki unter _https://wiki.fhem.de/wiki/Thin_Client_Hardware[Thin Client Hardware]_ eine Installationsanleitung für FHEM unter Debian, die zwar bereits 2017 erschienen ist, aber im Kern immer noch für alle x86-basierten Systeme gültig und aktuell ist.

.Hintergrund
****
Dein Server wird im Hintergrund laufen, wie z.B. auch dein Router (z.B. _FritzBox_). Hast du an den schon mal einen Bildschirm angeschlossen?!? Siehst du - das ist für ein Serversystem nicht nötig! Man aktiviert eine Zugriffsmöglichkeit aus dem Netzwerk namens *ssh* und administriert das ganze Betriebssystem dann über die Kommandozeile. Programme wie FHEM kann man dann über den Browser einrichten - ganz genau so, wie du das von deinem Router her kennst!

Sofern du jetzt denkst: _„Okay, habe ich gehört, aber eine GUI zu haben, kann ja nicht schaden?!?“_: Doch, kann es! Das sind Programmpakete, die du installierst, und auch diese können Fehler und Angriffsflächen für potentielle Eindringlinge enthalten! Sie sind daher ein *latentes Sicherheitsrisiko*. Das mag übertrieben klingen, ist aber eine Tatsache. Mache es dir ganz allgemein zum Grundsatz, nur Dinge zu installieren, die du für deine Vorhaben UNBEDINGT benötigst! Nicht mehr, nur das!
****

Als *absolutes Grundlagenwissen* zu Linux sind folgende deutschsprachigen Artikel bei https://wiki.ubuntuusers.de/[Ubuntuusers] zu empfehlen:

* https://wiki.ubuntuusers.de/Benutzer_und_Gruppen/[Benutzer und Gruppen]
* https://wiki.ubuntuusers.de/sudo/[sudo]
* https://wiki.ubuntuusers.de/man/[manpages]

Die Informationen von https://ubuntuusers.de[Ubuntuusers.de] sind fast immer ohne weiteres auch auf andere Debian-Derivate (also v.a. auch auf Raspbian) übertragbar, dies sollte also deine erste Anlaufstelle sein, wenn du Informationen zu deinem Server-Betriebssystem suchst.

Ein wichtiger *Merksatz* aus der Linux-Welt hat mir immer wieder geholfen: *_Alles ist eine Datei!_* Das bedeutet nicht mehr, aber auch nicht weniger, dass jede in einem Linux-System verfügbare Information _irgendwo unter /_ zu finden ist und damit auch _irgendwem_ gehört und z.B. außer diesem bestimmten _user_ nur _Mitglieder_ bestimmter _Gruppen_ auf diese Information zugreifen dürfen. Dies verstanden zu haben bedeutet, etwa 70% der Probleme [underline]#nicht# zu haben, über die Linux-Einsteiger gerne stolpern. Also falls du nicht weiterkommst, könntest du zuerst über *_alles ist eine Datei_* nachdenken.

Eine kleine Auswahl an Programmen, die dir das Leben mit einem Linux-Server erleichtern können, sind im Anhang unter link:#nützliches-tools-und-fundstücke[Nützliches] zu finden. Dort findet sich auch ein kurzes HowTo zu link:#ssh[ssh]-Verbindungen von Windows, über die du künftig hin und wieder Administrationsaufgaben an dem Server selbst erledigen wirst.

Hast du einen Rechner besorgt und den mit einem Debian-basierten Linux aufgesetzt, installierst du jetzt FHEM, am einfachsten über den *_easy way_*, wie er unter https://debian.fhem.de[debian.fhem.de] beschrieben ist - falls du kein Englisch sprichst: Nicht verzagen, nach dem Klick auf _easy way_ erscheinen nur ein paar Kommandos, die du einfach abschreiben kannst, aber mit den richtigen Rechten ausführen musst - _sudo_ kennst du ja bereits. Dabei solltest du dir merken, unter welcher IP-Adresse bzw. unter welchem Namen dein FHEM-Server im lokalen Netzwerk zu erreichen ist. Wenn du einen Pi nutzt, solltest du (neben Selbsverständlichkeiten wie dem Passwort und eventuell dem Usernamen pi!) den _hostname_ anpassen, normale Linux-Distributionen fragen ausdrücklich danach. Im Folgenden gehe ich davon aus, dass der Server als _fhem_server_ angesprochen werden kann. +
_Ok, fassen wir zusammen:_ Wir haben jetzt (vorläufig) einen Server (wenn es kein „Spielsystem“ ist: Ohne GUI) und FHEM kannst du entweder manuell als Perl-Script aus dem entpackten Verzeichnis starten, oder es wurde durch die Installation des Debian-Pakets automatisch in die Startmechanismen des Servers eingebunden (heute in der Regel in den https://wiki.ubuntuusers.de/systemd[systemd]-Dienst).
